{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Piedra, papel, tijeras\n",
    "\n",
    "Vamos jugar contra nuestro ordenador al famoso juego. \n",
    "\n",
    "https://es.wikipedia.org/wiki/Piedra,_papel_o_tijera\n",
    "\n",
    "Se aconseja el uso de funciones"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 49,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Importa la función choice del módulo random\n",
    "# https://stackoverflow.com/questions/306400/how-to-randomly-select-an-item-from-a-list\n",
    "\n",
    "\n",
    "# Asigna a una lista las 3 posibles opciones: 'piedra', 'papel' o 'tijeras'. \n",
    "\n",
    "\n",
    "# Asigna una variable al número de partidas máxima: 1, 3, 5, etc...\n",
    "\n",
    "\n",
    "# Asigna una variable al número de partidas que debe ganar un jugador para ganar. \n",
    "# Preferiblemente el valor será en función de el número de partidas máximas\n",
    "\n",
    "\n",
    "# Define una función que devuelva aleatoriamente una de las 3 opciones. \n",
    "# Esto corresponderá a la jugada de la máquina. Totalmente aleatoria. \n",
    "\n",
    "\n",
    "# Define una función que pregunte tu elección: 'piedra', 'papel' o 'tijeras'\n",
    "# sólo debe permitir una de las 3 opciones. Esto es programación defensiva. \n",
    "# Si no es piedra, papel o tijeras sigue preguntando hasta que lo sea. \n",
    "\n",
    "\n",
    "# Define una función que resuelva un combate. \n",
    "# Devuelve 0 si hay empate, 1 si gana la máquina, 2 si gana el jugador humano \n",
    "\n",
    "    \n",
    "# Define una función que muestre la elección de cada jugador y el estado de la partida\n",
    "# Esta función debe utilizarse cada vez que se actualicen los puntos acumulados\n",
    "\n",
    "    \n",
    "# Crea dos variables que acumulen las partidas ganadas de cada participante\n",
    "\n",
    "\n",
    "# Crea un bucle que itere mientras ningún jugador alcance el mínimo de victorias\n",
    "# necesarias para ganar. Dentro del bucle resuelve la jugada de la\n",
    "# máquina y pregunta la del jugador. Comparalas y actualiza el valor de las variables\n",
    "# que acumulen las partidas ganadas de cada participante. \n",
    "\n",
    "    \n",
    "# Anuncia por consola el ganador del juego en función de quién tiene más victorias \n",
    "# aculumadas\n",
    "\n",
    "    "
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Bonus: Piedra, papel, tijeras, lagarto, spock\n",
    "\n",
    "Ahora vienen las mejoras. \n",
    "\n",
    "http://www.samkass.com/theories/RPSSL.html\n",
    "\n",
    "Se te pide que implimentes unas mejoras con respecto al simple juego previo. Además el número de partidas (que deberá ser IMPAR) se pedirá por consola hasta que se introduzca un número válido. \n",
    "\n",
    "Mejoras: \n",
    "* 5 opciones: piedra, papel, tijeras, lagarto, spock\n",
    "* El número de partidas se pide por consola\n",
    "Consejo: Reutiliza código que ya hagas utilizado"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Importa la función choice del módulo random\n",
    "\n",
    "\n",
    "# Define una función que pide por teclado un número impar, hasta que no sea válido\n",
    "# seguirá pidiendo\n",
    "\n",
    "\n",
    "# Asigna a una lista las 5 posibles opciones. \n",
    "\n",
    "\n",
    "# Asigna una variable al número de partidas máxima: 1, 3, 5, etc...\n",
    "# Esta vez se usa la función definida previamente\n",
    "\n",
    "\n",
    "# Asigna una variable al número de partidas que debe ganar un jugador para ganar. \n",
    "# Preferiblemente el valor será en función de el número de partidas máximas\n",
    "\n",
    "\n",
    "# Define una función que devuelva aleatoriamente una de las 5 opciones. \n",
    "# Esto corresponderá a la jugada de la máquina. Totalmente aleatoria. \n",
    "\n",
    "\n",
    "\n",
    "# Define una función que pregunte tu elección de entre las 5\n",
    "# sólo debe permitir una de las 5 opciones. Esto es programación defensiva. \n",
    "# Si no es válida sigue preguntando hasta que lo sea. \n",
    "\n",
    "\n",
    "# Define una función que resuelva un combate. \n",
    "# Devuelve 0 si hay empate, 1 si gana la máquina, 2 si gana el jugador humano\n",
    "# Ahora hay más opciones\n",
    "\n",
    "\n",
    "    \n",
    "# Define una función que muestre la elección de cada jugador y el estado de la partida\n",
    "# Esta función debe utilizarse cada vez que se actualicen los puntos acumulados\n",
    "\n",
    "\n",
    "    \n",
    "# Crea dos variables que acumulen las partidas ganadas de cada participante\n",
    "\n",
    "\n",
    "# Crea un bucle que itere mientras ningún jugador alcance el mínimo de victorias\n",
    "# necesarias para ganar. Dentro del bucle resuelve la jugada de la\n",
    "# máquina y pregunta la del jugador. Comparalas y actualiza el valor de las variables\n",
    "# que acumulen las partidas ganadas de cada participante. \n",
    "\n",
    "\n",
    "    \n",
    "# Anuncia por consola el ganador del juego en función de quién tiene más victorias \n",
    "# aculumadas\n",
    "\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Si has programado con cabeza, el bonus son simples modificaciones al juego original. "
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Objetivos\n",
    "1. Uso de bucle\n",
    "2. Captura de datos por consola\n",
    "3. Uso if-elif-else\n",
    "4. Uso de try-except\n",
    "5. Definición de funciones. Programación modular. \n",
    "6. Operadores lógicos. \n",
    "7. Imprimir por consola\n",
    "8. Importación de módulos externos"
   ]
  },
  {
   "source": [
    "# SOLUCIÓN "
   ],
   "cell_type": "markdown",
   "metadata": {}
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Crea dos variables que acumulen las partidas ganadas de cada participante\n",
    "\n",
    "partidasganadasusuario = 0\n",
    "partidasganadasmaquina = 0 \n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "output_type": "stream",
     "name": "stdout",
     "text": "ception occurred:\n\nTraceback (most recent call last):\n  File \"<ipython-input-2-68e46cc7784f>\", line 14, in partidasmax\nValueError: invalid literal for int() with base 10: ''\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"<ipython-input-2-68e46cc7784f>\", line 14, in partidasmax\nValueError: invalid literal for int() with base 10: ''\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"<ipython-input-2-68e46cc7784f>\", line 14, in partidasmax\nValueError: invalid literal for int() with base 10: ''\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"<ipython-input-2-68e46cc7784f>\", line 14, in partidasmax\nValueError: invalid literal for int() with base 10: ''\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"<ipython-input-2-68e46cc7784f>\", line 14, in partidasmax\nValueError: invalid literal for int() with base 10: ''\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"<ipython-input-2-68e46cc7784f>\", line 14, in partidasmax\nValueError: invalid literal for int() with base 10: ''\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"<ipython-input-2-68e46cc7784f>\", line 14, in partidasmax\nValueError: invalid literal for int() with base 10: ''\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"<ipython-input-2-68e46cc7784f>\", line 14, in partidasmax\nValueError: invalid literal for int() with base 10: ''\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"<ipython-input-2-68e46cc7784f>\", line 14, in partidasmax\nValueError: invalid literal for int() with base 10: ''\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"<ipython-input-2-68e46cc7784f>\", line 14, in partidasmax\nValueError: invalid literal for int() with base 10: ''\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"<ipython-input-2-68e46cc7784f>\", line 14, in partidasmax\nValueError: invalid literal for int() with base 10: ''\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"<ipython-input-2-68e46cc7784f>\", line 14, in partidasmax\nValueError: invalid literal for int() with base 10: ''\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"<ipython-input-2-68e46cc7784f>\", line 14, in partidasmax\nValueError: invalid literal for int() with base 10: ''\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"<ipython-input-2-68e46cc7784f>\", line 14, in partidasmax\nValueError: invalid literal for int() with base 10: ''\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"<ipython-input-2-68e46cc7784f>\", line 14, in partidasmax\nValueError: invalid literal for int() with base 10: ''\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"<ipython-input-2-68e46cc7784f>\", line 14, in partidasmax\nValueError: invalid literal for int() with base 10: ''\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"<ipython-input-2-68e46cc7784f>\", line 14, in partidasmax\nValueError: invalid literal for int() with base 10: ''\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"<ipython-input-2-68e46cc7784f>\", line 14, in partidasmax\nValueError: invalid literal for int() with base 10: ''\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"<ipython-input-2-68e46cc7784f>\", line 14, in partidasmax\nValueError: invalid literal for int() with base 10: ''\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"<ipython-input-2-68e46cc7784f>\", line 14, in partidasmax\nValueError: invalid literal for int() with base 10: ''\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"<ipython-input-2-68e46cc7784f>\", line 14, in partidasmax\nValueError: invalid literal for int() with base 10: ''\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"<ipython-input-2-68e46cc7784f>\", line 14, in partidasmax\nValueError: invalid literal for int() with base 10: ''\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"<ipython-input-2-68e46cc7784f>\", line 14, in partidasmax\nValueError: invalid literal for int() with base 10: ''\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"<ipython-input-2-68e46cc7784f>\", line 14, in partidasmax\nValueError: invalid literal for int() with base 10: ''\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"<ipython-input-2-68e46cc7784f>\", line 14, in partidasmax\nValueError: invalid literal for int() with base 10: ''\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"<ipython-input-2-68e46cc7784f>\", line 14, in partidasmax\nValueError: invalid literal for int() with base 10: ''\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"<ipython-input-2-68e46cc7784f>\", line 14, in partidasmax\nValueError: invalid literal for int() with base 10: ''\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"<ipython-input-2-68e46cc7784f>\", line 14, in partidasmax\nValueError: invalid literal for int() with base 10: ''\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"<ipython-input-2-68e46cc7784f>\", line 14, in partidasmax\nValueError: invalid literal for int() with base 10: ''\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"<ipython-input-2-68e46cc7784f>\", line 14, in partidasmax\nValueError: invalid literal for int() with base 10: ''\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"<ipython-input-2-68e46cc7784f>\", line 14, in partidasmax\nValueError: invalid literal for int() with base 10: ''\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"<ipython-input-2-68e46cc7784f>\", line 14, in partidasmax\nValueError: invalid literal for int() with base 10: ''\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"<ipython-input-2-68e46cc7784f>\", line 14, in partidasmax\nValueError: invalid literal for int() with base 10: ''\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"<ipython-input-2-68e46cc7784f>\", line 14, in partidasmax\nValueError: invalid literal for int() with base 10: ''\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"<ipython-input-2-68e46cc7784f>\", line 14, in partidasmax\nValueError: invalid literal for int() with base 10: ''\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"<ipython-input-2-68e46cc7784f>\", line 18, in partidasmax\n  File \"<ipython-input-2-68e46cc7784f>\", line 18, in partidasmax\n  File \"<ipython-input-2-68e46cc7784f>\", line 18, in partidasmax\n  [Previous line repeated 991 more times]\n  File \"<ipython-input-2-68e46cc7784f>\", line 12, in partidasmax\n  File \"C:\\Users\\enrique.gomez\\AppData\\Roaming\\Python\\Python38\\site-packages\\ipykernel\\kernelbase.py\", line 860, in raw_input\n    return self._input_request(str(prompt),\n  File \"C:\\Users\\enrique.gomez\\AppData\\Roaming\\Python\\Python38\\site-packages\\ipykernel\\kernelbase.py\", line 868, in _input_request\n    sys.stderr.flush()\n  File \"C:\\Users\\enrique.gomez\\AppData\\Roaming\\Python\\Python38\\site-packages\\ipykernel\\iostream.py\", line 352, in flush\n    if not evt.wait(self.flush_timeout):\n  File \"C:\\Users\\enrique.gomez\\Anaconda3\\lib\\threading.py\", line 558, in wait\n    signaled = self._cond.wait(timeout)\n  File \"C:\\Users\\enrique.gomez\\Anaconda3\\lib\\threading.py\", line 306, in wait\n    gotit = waiter.acquire(True, timeout)\nKeyboardInterrupt\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\enrique.gomez\\AppData\\Roaming\\Python\\Python38\\site-packages\\IPython\\core\\interactiveshell.py\", line 2044, in showtraceback\n    stb = value._render_traceback_()\nAttributeError: 'KeyboardInterrupt' object has no attribute '_render_traceback_'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\enrique.gomez\\Anaconda3\\lib\\genericpath.py\", line 19, in exists\n    os.stat(path)\nOSError: [WinError 123] El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos: '<ipython-input-2-68e46cc7784f>'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\enrique.gomez\\AppData\\Roaming\\Python\\Python38\\site-packages\\IPython\\core\\ultratb.py\", line 1169, in get_records\n    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n  File \"C:\\Users\\enrique.gomez\\AppData\\Roaming\\Python\\Python38\\site-packages\\IPython\\core\\ultratb.py\", line 316, in wrapped\n    return f(*args, **kwargs)\n  File \"C:\\Users\\enrique.gomez\\AppData\\Roaming\\Python\\Python38\\site-packages\\IPython\\core\\ultratb.py\", line 350, in _fixed_getinnerframes\n    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n  File \"C:\\Users\\enrique.gomez\\Anaconda3\\lib\\inspect.py\", line 1503, in getinnerframes\n    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n  File \"C:\\Users\\enrique.gomez\\Anaconda3\\lib\\inspect.py\", line 1465, in getframeinfo\n    lines, lnum = findsource(frame)\n  File \"C:\\Users\\enrique.gomez\\AppData\\Roaming\\Python\\Python38\\site-packages\\IPython\\core\\ultratb.py\", line 170, in findsource\n    file = getsourcefile(object) or getfile(object)\n  File \"C:\\Users\\enrique.gomez\\Anaconda3\\lib\\inspect.py\", line 705, in getsourcefile\n    if os.path.exists(filename):\n  File \"C:\\Users\\enrique.gomez\\Anaconda3\\lib\\genericpath.py\", line 19, in exists\n    os.stat(path)\nKeyboardInterrupt\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\enrique.gomez\\Anaconda3\\lib\\traceback.py\", line 493, in __init__\n    context = TracebackException(\n  File \"C:\\Users\\enrique.gomez\\Anaconda3\\lib\\traceback.py\", line 493, in __init__\n    context = TracebackException(\n  File \"C:\\Users\\enrique.gomez\\Anaconda3\\lib\\traceback.py\", line 493, in __init__\n    context = TracebackException(\n  [Previous line repeated 997 more times]\nRecursionError: maximum recursion depth exceeded\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\enrique.gomez\\AppData\\Roaming\\Python\\Python38\\site-packages\\IPython\\core\\interactiveshell.py\", line 2044, in showtraceback\n    stb = value._render_traceback_()\nAttributeError: 'RecursionError' object has no attribute '_render_traceback_'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\enrique.gomez\\Anaconda3\\lib\\genericpath.py\", line 19, in exists\n    os.stat(path)\nOSError: [WinError 123] El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos: '<ipython-input-2-68e46cc7784f>'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\enrique.gomez\\AppData\\Roaming\\Python\\Python38\\site-packages\\IPython\\core\\ultratb.py\", line 1169, in get_records\n    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n  File \"C:\\Users\\enrique.gomez\\AppData\\Roaming\\Python\\Python38\\site-packages\\IPython\\core\\ultratb.py\", line 316, in wrapped\n    return f(*args, **kwargs)\n  File \"C:\\Users\\enrique.gomez\\AppData\\Roaming\\Python\\Python38\\site-packages\\IPython\\core\\ultratb.py\", line 350, in _fixed_getinnerframes\n    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n  File \"C:\\Users\\enrique.gomez\\Anaconda3\\lib\\inspect.py\", line 1503, in getinnerframes\n    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n  File \"C:\\Users\\enrique.gomez\\Anaconda3\\lib\\inspect.py\", line 1461, in getframeinfo\n    filename = getsourcefile(frame) or getfile(frame)\n  File \"C:\\Users\\enrique.gomez\\Anaconda3\\lib\\inspect.py\", line 705, in getsourcefile\n    if os.path.exists(filename):\n  File \"C:\\Users\\enrique.gomez\\Anaconda3\\lib\\genericpath.py\", line 19, in exists\n    os.stat(path)\nKeyboardInterrupt\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\enrique.gomez\\Anaconda3\\lib\\traceback.py\", line 493, in __init__\n    context = TracebackException(\n  File \"C:\\Users\\enrique.gomez\\Anaconda3\\lib\\traceback.py\", line 493, in __init__\n    context = TracebackException(\n  File \"C:\\Users\\enrique.gomez\\Anaconda3\\lib\\traceback.py\", line 493, in __init__\n    context = TracebackException(\n  [Previous line repeated 996 more times]\n  File \"C:\\Users\\enrique.gomez\\Anaconda3\\lib\\traceback.py\", line 476, in __init__\n    _seen.add(id(exc_value))\nRecursionError: maximum recursion depth exceeded while calling a Python object\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\enrique.gomez\\AppData\\Roaming\\Python\\Python38\\site-packages\\IPython\\core\\interactiveshell.py\", line 2044, in showtraceback\n    stb = value._render_traceback_()\nAttributeError: 'RecursionError' object has no attribute '_render_traceback_'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\enrique.gomez\\Anaconda3\\lib\\genericpath.py\", line 19, in exists\n    os.stat(path)\nOSError: [WinError 123] El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos: '<ipython-input-2-68e46cc7784f>'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\enrique.gomez\\AppData\\Roaming\\Python\\Python38\\site-packages\\IPython\\core\\ultratb.py\", line 1169, in get_records\n    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n  File \"C:\\Users\\enrique.gomez\\AppData\\Roaming\\Python\\Python38\\site-packages\\IPython\\core\\ultratb.py\", line 316, in wrapped\n    return f(*args, **kwargs)\n  File \"C:\\Users\\enrique.gomez\\AppData\\Roaming\\Python\\Python38\\site-packages\\IPython\\core\\ultratb.py\", line 350, in _fixed_getinnerframes\n    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n  File \"C:\\Users\\enrique.gomez\\Anaconda3\\lib\\inspect.py\", line 1503, in getinnerframes\n    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n  File \"C:\\Users\\enrique.gomez\\Anaconda3\\lib\\inspect.py\", line 1465, in getframeinfo\n    lines, lnum = findsource(frame)\n  File \"C:\\Users\\enrique.gomez\\AppData\\Roaming\\Python\\Python38\\site-packages\\IPython\\core\\ultratb.py\", line 170, in findsource\n    file = getsourcefile(object) or getfile(object)\n  File \"C:\\Users\\enrique.gomez\\Anaconda3\\lib\\inspect.py\", line 705, in getsourcefile\n    if os.path.exists(filename):\n  File \"C:\\Users\\enrique.gomez\\Anaconda3\\lib\\genericpath.py\", line 19, in exists\n    os.stat(path)\nKeyboardInterrupt\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\enrique.gomez\\Anaconda3\\lib\\traceback.py\", line 493, in __init__\n    context = TracebackException(\n  File \"C:\\Users\\enrique.gomez\\Anaconda3\\lib\\traceback.py\", line 493, in __init__\n    context = TracebackException(\n  File \"C:\\Users\\enrique.gomez\\Anaconda3\\lib\\traceback.py\", line 493, in __init__\n    context = TracebackException(\n  [Previous line repeated 996 more times]\n  File \"C:\\Users\\enrique.gomez\\Anaconda3\\lib\\traceback.py\", line 476, in __init__\n    _seen.add(id(exc_value))\nRecursionError: maximum recursion depth exceeded while calling a Python object\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\enrique.gomez\\Anaconda3\\lib\\traceback.py\", line 493, in __init__\n    context = TracebackException(\n  File \"C:\\Users\\enrique.gomez\\Anaconda3\\lib\\traceback.py\", line 493, in __init__\n    context = TracebackException(\n  File \"C:\\Users\\enrique.gomez\\Anaconda3\\lib\\traceback.py\", line 493, in __init__\n    context = TracebackException(\n  [Previous line repeated 997 more times]\nRecursionError: maximum recursion depth exceeded\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\enrique.gomez\\Anaconda3\\lib\\traceback.py\", line 493, in __init__\n    context = TracebackException(\n  File \"C:\\Users\\enrique.gomez\\Anaconda3\\lib\\traceback.py\", line 493, in __init__\n    context = TracebackException(\n  File \"C:\\Users\\enrique.gomez\\Anaconda3\\lib\\traceback.py\", line 493, in __init__\n    context = TracebackException(\n  [Previous line repeated 996 more times]\n  File \"C:\\Users\\enrique.gomez\\Anaconda3\\lib\\traceback.py\", line 476, in __init__\n    _seen.add(id(exc_value))\nRecursionError: maximum recursion depth exceeded while calling a Python object\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\enrique.gomez\\Anaconda3\\lib\\traceback.py\", line 493, in __init__\n    context = TracebackException(\n  File \"C:\\Users\\enrique.gomez\\Anaconda3\\lib\\traceback.py\", line 493, in __init__\n    context = TracebackException(\n  File \"C:\\Users\\enrique.gomez\\Anaconda3\\lib\\traceback.py\", line 493, in __init__\n    context = TracebackException(\n  [Previous line repeated 997 more times]\nRecursionError: maximum recursion depth exceeded\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\enrique.gomez\\Anaconda3\\lib\\traceback.py\", line 493, in __init__\n    context = TracebackException(\n  File \"C:\\Users\\enrique.gomez\\Anaconda3\\lib\\traceback.py\", line 493, in __init__\n    context = TracebackException(\n  File \"C:\\Users\\enrique.gomez\\Anaconda3\\lib\\traceback.py\", line 493, in __init__\n    context = TracebackException(\n  [Previous line repeated 996 more times]\n  File \"C:\\Users\\enrique.gomez\\Anaconda3\\lib\\traceback.py\", line 476, in __init__\n    _seen.add(id(exc_value))\nRecursionError: maximum recursion depth exceeded while calling a Python object\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\enrique.gomez\\Anaconda3\\lib\\traceback.py\", line 493, in __init__\n    context = TracebackException(\n  File \"C:\\Users\\enrique.gomez\\Anaconda3\\lib\\traceback.py\", line 493, in __init__\n    context = TracebackException(\n  File \"C:\\Users\\enrique.gomez\\Anaconda3\\lib\\traceback.py\", line 493, in __init__\n    context = TracebackException(\n  [Previous line repeated 997 more times]\nRecursionError: maximum recursion depth exceeded\n"
    }
   ],
   "source": [
    "import random as rd\n",
    "import math\n",
    "\n",
    "# Listas\n",
    "\n",
    "opciones = [\"piedra\", \"papel\", \"tijeras\"] #opciones del juego \n",
    "\n",
    "\n",
    "# Funciones\n",
    "\n",
    "def partidasmax(): \n",
    "    partidas = input(\"¿Cuántas partidas quieres jugar?\") # Partidas máximas. \n",
    "    try:\n",
    "        entero = int(partidas)\n",
    "        return int(partidas)\n",
    "    except ValueError:                         \n",
    "        print(\"No es un formato correcto\")\n",
    "        return partidasmax()\n",
    "\n",
    "def partidasvictoria(a): # define el numero de partidas necesarias para la victoria\n",
    "    if a%2 == 0:\n",
    "        return a/2 + 1\n",
    "    else:\n",
    "        return math.ceil(a/2)\n",
    "\n",
    "def eleccionaleatoria():  # Define una función que devuelva aleatoriamente una de las 3 opciones. \n",
    "    return rd.choice(opciones)\n",
    "\n",
    "def eleccion(): # Define una función que pregunte tu elección: 'piedra', 'papel' o 'tijeras'\n",
    "    a = input(\"¿Cuál es tu elección Piedra Papel o Tijeras?\")\n",
    "    a = a.lower()\n",
    "    if str(a) is opciones:\n",
    "        return a\n",
    "    else:\n",
    "        print(\"El nombre introducido no es correcto\")\n",
    "        return eleccion()\n",
    "\n",
    "def combate():  # Define una función que rasigne valores a los vencedores del combate\n",
    "    x = eleccion_maquina\n",
    "    y = eleccion_usuario\n",
    "    if x == 'tijeras' and y == 'papel':\n",
    "        return print(1)\n",
    "    elif x == 'tijeras' and y == 'piedra':\n",
    "        return print(2)\n",
    "    elif x == 'piedra' and y == 'papel':\n",
    "        return print(2)\n",
    "    elif  y == 'tijeras' and x == 'papel':\n",
    "        return print(2)\n",
    "    elif y == 'tijeras' and x == 'piedra':\n",
    "        return print(1)\n",
    "    elif y == 'piedra' and x == 'papel':\n",
    "        return print(1)\n",
    "    elif x == y:\n",
    "        return print(0)\n",
    "\n",
    "# Define una función que muestre la elección de cada jugador y el estado de la partida\n",
    "\n",
    "\n",
    "\n",
    "# Variables\n",
    "\n",
    "partidas_maximas = partidasmax()\n",
    "partidas_victoria = partidasvictoria(partidas_maximas)\n",
    "eleccion_maquina = eleccionaleatoria()\n",
    "eleccion_usuario = eleccion()\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.3-final"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}